include:
  - project: 'sysadm-docker/ubuntu-sshclient'
    ref:     'master'
    file:    'gitlab-ci-template.yml'
  - project: 'security/security-tools'
    ref: 'v2'
    file: 'adapter/sdk/security-tools-store-ue4-sdk.yml'

stages:
  - build
  - security scan
  - deploy
  - linking
  - demo_win
  - demo_android
  - demo_ios

variables:
    BUILD_DEMO_SCRIPT: cicd/build_demo.py
    BUILD_DEMO_SCRIPT2: 1

# =================================================================================================================
# DOCS

build doc:
  stage: build
  only:
    - /^v.*/
  image: node:14-alpine3.15
  script:
  - apk update && apk add doxygen graphviz ttf-freefont zip git
  - doxygen Documentation/Autogen/Doxyfile >/dev/null
  - git clone https://$GITHUB_ACCESS_TOKEN@github.com/xsolla/sdk-reference-parser-unity-ue.git
  - mkdir -p sdk-reference-parser-unity-ue/src
  - mkdir -p sdk-reference-parser-unity-ue/dist
  - mv Documentation/Autogen/html/ sdk-reference-parser-unity-ue/src >/dev/null
  - cd sdk-reference-parser-unity-ue
  - npm install
  - npm start
  - mv -v dist/html/* dist >/dev/null
  - cd dist && zip -r $CI_PROJECT_DIR/build.zip * >/dev/null
  artifacts:
    paths:
    - build.zip
  tags:
    - devops

deploy doc:
  stage: deploy
  extends:      .deploy doc
  only:
    - /^v.*/
  dependencies:
    - build doc
  environment:
    name: doc/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.doc.srv.local/$URL_SLUG
    on_stop: stop doc
  when: manual
  tags:
    - sshclient

current doc:
  extends:      .current doc
  only:
    - /^v.*/
  dependencies:
    - deploy doc
  environment:
    name: doc/current
    url: https://developers.xsolla.com/sdk-code-references/unreal-store/
  tags:
    - sshclient

stop doc:
  extends:      .stop doc
  environment:
    name: doc/$CI_COMMIT_REF_SLUG
    action: stop
  only:
    - /^v.*/
  dependencies: []
  tags:
    - sshclient

# =================================================================================================================
# JOBS BASE

.win_job_base:
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - Builds
  dependencies: []
  tags:
    - sdk_ci
    - windows

.mac_job_base:
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - Builds
  dependencies: []
  tags:
    - sdk_ci
    - mac

# =================================================================================================================
# DEMO WINIDOWS

demo_52_win_inapp_browser:
  extends: .win_job_base
  stage: demo_win
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.2" Win64 False
  artifacts:
    name: "demo-UE52-win-inapp_browser-%CI_COMMIT_REF_SLUG%"

demo_52_win_system_browser:
  extends: .win_job_base
  stage: demo_win
  when: manual
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.2" Win64 True
  artifacts:
    name: "demo-UE52-win-system_browser-%CI_COMMIT_REF_SLUG%"
    
demo_53_win_inapp_browser:
  extends: .win_job_base
  stage: demo_win
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.3" Win64 False
  artifacts:
    name: "demo-UE53-win-inapp_browser-%CI_COMMIT_REF_SLUG%"

demo_53_win_system_browser:
  extends: .win_job_base
  stage: demo_win
  when: manual
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.3" Win64 True
  artifacts:
    name: "demo-UE53-win-system_browser-%CI_COMMIT_REF_SLUG%"
    
demo_54_win_inapp_browser:
  extends: .win_job_base
  stage: demo_win
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.4" Win64 False
  artifacts:
    name: "demo-UE54-win-inapp_browser-%CI_COMMIT_REF_SLUG%"

demo_54_win_system_browser:
  extends: .win_job_base
  stage: demo_win
  when: manual
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.4" Win64 True
  artifacts:
    name: "demo-UE54-win-system_browser-%CI_COMMIT_REF_SLUG%"
    
demo_55_win_inapp_browser:
  extends: .win_job_base
  stage: demo_win
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.5" Win64 False
  artifacts:
    name: "demo-UE55-win-inapp_browser-%CI_COMMIT_REF_SLUG%"

demo_55_win_system_browser:
  extends: .win_job_base
  stage: demo_win
  when: manual
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.5" Win64 True
  artifacts:
    name: "demo-UE55-win-system_browser-%CI_COMMIT_REF_SLUG%"

# =================================================================================================================
# DEMO ANDROID

demo_52_android_inapp_browser:
  extends: .win_job_base
  stage: demo_android
  when: manual
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.2" Android False
  artifacts:
    name: "demo-UE52-android-inapp_browser-%CI_COMMIT_REF_SLUG%"

demo_52_android_system_browser:
  extends: .win_job_base
  stage: demo_android
  when: manual
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.2" Android True
  artifacts:
    name: "demo-UE52-android-system_browser-%CI_COMMIT_REF_SLUG%"
    
demo_53_android_inapp_browser:
  extends: .win_job_base
  stage: demo_android
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.3" Android False
  artifacts:
    name: "demo-UE53-android-inapp_browser-%CI_COMMIT_REF_SLUG%"

demo_53_android_system_browser:
  extends: .win_job_base
  stage: demo_android
  when: manual
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.3" Android True
  artifacts:
    name: "demo-UE53-android-system_browser-%CI_COMMIT_REF_SLUG%"
    
demo_54_android_inapp_browser:
  extends: .win_job_base
  stage: demo_android
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.4" Android False
  artifacts:
    name: "demo-UE54-android-inapp_browser-%CI_COMMIT_REF_SLUG%"

demo_54_android_system_browser:
  extends: .win_job_base
  stage: demo_android
  when: manual
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.4" Android True
  artifacts:
    name: "demo-UE54-android-system_browser-%CI_COMMIT_REF_SLUG%"
    
demo_55_android_inapp_browser:
  extends: .win_job_base
  stage: demo_android
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.5" Android False
  artifacts:
    name: "demo-UE55-android-inapp_browser-%CI_COMMIT_REF_SLUG%"

demo_55_android_system_browser:
  extends: .win_job_base
  stage: demo_android
  when: manual
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.5" Android True
  artifacts:
    name: "demo-UE55-android-system_browser-%CI_COMMIT_REF_SLUG%"

# =================================================================================================================
# DEMO IOS

demo_52_ios_inapp_browser:
  extends: .mac_job_base
  stage: demo_ios
  script:
    - python3 $BUILD_DEMO_SCRIPT $CI_PROJECT_DIR $CI_COMMIT_REF_NAME "5.2" IOS False
  artifacts:
    name: "demo-UE52-ios-inapp_browser-$CI_COMMIT_REF_SLUG"

demo_52_ios_system_browser:
  extends: .mac_job_base
  stage: demo_ios
  when: manual
  script:
    - python3 $BUILD_DEMO_SCRIPT $CI_PROJECT_DIR $CI_COMMIT_REF_NAME "5.2" IOS True
  artifacts:
    name: "demo-UE52-ios-system_browser-$CI_COMMIT_REF_SLUG"
