include:
  - project: 'sysadm-docker/ubuntu-sshclient'
    ref:     'master'
    file:    'gitlab-ci-template.yml'
  - project: 'security/security-tools'
    ref: 'v2'
    file: 'adapter/sdk/security-tools-store-ue4-sdk.yml'

stages:
  - build
  - security scan
  - deploy
  - linking
  - demo_win
  - demo_android
  - demo_mac

variables:
    BUILD_DEMO_SCRIPT: cicd/build_demo.py
    ANDROID_SDK_ROOT: "C:\\Users\\Runner\\AppData\\Local\\Android\\Sdk"
    JAVA_PATH_8:  "C:\\Program Files\\Java\\jdk1.8.0_181"
    JAVA_PATH_17: "C:\\Program Files\\Java\\jdk-17"
    NDK_PATH_25: "C:\\Users\\Runner\\AppData\\Local\\Android\\Sdk\\ndk\\25.1.8937393"
    NDK_PATH_27: "C:\\Users\\Runner\\AppData\\Local\\Android\\Sdk\\ndk\\27.2.12479018"

# =================================================================================================================
# DOCS

build doc:
  stage: build
  only:
    - /^v.*/
  image: node:14-alpine3.15
  script:
  - apk update && apk add doxygen graphviz ttf-freefont zip git
  - doxygen Documentation/Autogen/Doxyfile >/dev/null
  - cd Documentation/Autogen/html && zip -r $CI_PROJECT_DIR/build.zip * >/dev/null
  artifacts:
    paths:
    - build.zip
  tags:
    - devops

deploy doc:
  stage: deploy
  extends:      .deploy doc
  only:
    - /^v.*/
  dependencies:
    - build doc
  environment:
    name: doc/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.doc.srv.local/$URL_SLUG
    on_stop: stop doc
  when: manual
  tags:
    - sshclient

current doc:
  extends:      .current doc
  only:
    - /^v.*/
  dependencies:
    - deploy doc
  environment:
    name: doc/current
    url: https://developers.xsolla.com/sdk-code-references/unreal-store/
  tags:
    - sshclient

stop doc:
  extends:      .stop doc
  environment:
    name: doc/$CI_COMMIT_REF_SLUG
    action: stop
  only:
    - /^v.*/
  dependencies: []
  tags:
    - sshclient

# =================================================================================================================
# JOBS BASE

.win_job_base:
  variables:
    JAVA_HOME: $JAVA_PATH_17
    NDK_PATH: $NDK_PATH_25
  allow_failure: true
  before_script:
    - set PATH=%JAVA_HOME%\bin;%PATH%
    - set PATH=%ANDROID_SDK_ROOT%\platform-tools;%ANDROID_SDK_ROOT%\tools;%NDK_PATH%;%PATH%
    - set NDK_ROOT=%NDK_PATH%
    - set NDKROOT=%NDK_PATH%
    - set ANDROID_NDK_ROOT=%NDK_PATH%
    - java -version
    - echo "JAVA_HOME=%JAVA_HOME%"
    - echo "ANDROID_SDK_ROOT=%ANDROID_SDK_ROOT%"
    - echo "NDK_PATH=%NDK_PATH%"
    - echo "NDKROOT=%NDKROOT%"
    - echo "NDK_ROOT=%NDK_ROOT%"
    - echo "ANDROID_NDK_ROOT=%ANDROID_NDK_ROOT%"
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - Builds
  dependencies: []
  tags:
    - sdk_ci
    - windows

.mac_job_base:
  allow_failure: true
  when: manual
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - Builds
  dependencies: []
  tags:
    - sdk_ci
    - mac

# =================================================================================================================
# DEMO WINIDOWS
    
demo_54_win_inapp_browser:
  extends: .win_job_base
  stage: demo_win
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.4" Win64 False
  artifacts:
    name: "demo-UE54-win-inapp_browser-%CI_COMMIT_REF_SLUG%"

demo_54_win_system_browser:
  extends: .win_job_base
  stage: demo_win
  when: manual
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.4" Win64 True
  artifacts:
    name: "demo-UE54-win-system_browser-%CI_COMMIT_REF_SLUG%"
    
demo_55_win_inapp_browser:
  extends: .win_job_base
  stage: demo_win
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.5" Win64 False
  artifacts:
    name: "demo-UE55-win-inapp_browser-%CI_COMMIT_REF_SLUG%"

demo_55_win_system_browser:
  extends: .win_job_base
  stage: demo_win
  when: manual
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.5" Win64 True
  artifacts:
    name: "demo-UE55-win-system_browser-%CI_COMMIT_REF_SLUG%"

demo_56_win_inapp_browser:
  extends: .win_job_base
  stage: demo_win
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.6" Win64 False
  artifacts:
    name: "demo-UE56-win-inapp_browser-%CI_COMMIT_REF_SLUG%"

demo_56_win_system_browser:
  extends: .win_job_base
  stage: demo_win
  when: manual
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.6" Win64 True
  artifacts:
    name: "demo-UE56-win-system_browser-%CI_COMMIT_REF_SLUG%"

# =================================================================================================================
# DEMO ANDROID

demo_54_android_inapp_browser:
  extends: .win_job_base
  stage: demo_android
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.4" Android False
  artifacts:
    name: "demo-UE54-android-inapp_browser-%CI_COMMIT_REF_SLUG%"

demo_54_android_system_browser:
  extends: .win_job_base
  stage: demo_android
  when: manual
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.4" Android True
  artifacts:
    name: "demo-UE54-android-system_browser-%CI_COMMIT_REF_SLUG%"
    
demo_55_android_inapp_browser:
  extends: .win_job_base
  stage: demo_android
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.5" Android False
  artifacts:
    name: "demo-UE55-android-inapp_browser-%CI_COMMIT_REF_SLUG%"

demo_55_android_system_browser:
  extends: .win_job_base
  stage: demo_android
  when: manual
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.5" Android True
  artifacts:
    name: "demo-UE55-android-system_browser-%CI_COMMIT_REF_SLUG%"

demo_56_android_inapp_browser:
  extends: .win_job_base
  stage: demo_android
  variables:
    NDK_PATH: $NDK_PATH_27
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.6" Android False
  artifacts:
    name: "demo-UE56-android-inapp_browser-%CI_COMMIT_REF_SLUG%"

demo_56_android_system_browser:
  extends: .win_job_base
  stage: demo_android
  variables:
    NDK_PATH: $NDK_PATH_27
  when: manual
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% "5.6" Android True
  artifacts:
    name: "demo-UE56-android-system_browser-%CI_COMMIT_REF_SLUG%"

# =================================================================================================================
# DEMO MAC

demo_52_mac_inapp_browser:
  extends: .mac_job_base
  stage: demo_mac
  script:
    - python3 $BUILD_DEMO_SCRIPT $CI_PROJECT_DIR $CI_COMMIT_REF_NAME "5.2" Mac False
  artifacts:
    name: "demo-UE52-mac-inapp_browser-$CI_COMMIT_REF_SLUG"

demo_52_mac_system_browser:
  extends: .mac_job_base
  stage: demo_mac
  script:
    - python3 $BUILD_DEMO_SCRIPT $CI_PROJECT_DIR $CI_COMMIT_REF_NAME "5.2" Mac True
  artifacts:
    name: "demo-UE52-mac-system_browser-$CI_COMMIT_REF_SLUG"