include:
  - project: 'sysadm-docker/ubuntu-sshclient'
    ref:     'master'
    file:    'gitlab-ci-template.yml'

stages:
  - build
  - deploy
  - linking
  - demo_win
  - demo_android
  - demo_ios

variables:
    BUILD_DEMO_SCRIPT: cicd/build_demo.py
    UE52_ENGINE_VERSION: "5.2"

# =================================================================================================================
# DOCS

build doc:
  stage: build
  only:
    - /^v.*/
  image: node:14-alpine3.15
  script:
  - apk update && apk add doxygen graphviz ttf-freefont zip git
  - doxygen Documentation/Autogen/Doxyfile >/dev/null
  - git clone https://$GITHUB_ACCESS_TOKEN@github.com/xsolla/sdk-reference-parser-unity-ue.git
  - mkdir -p sdk-reference-parser-unity-ue/src
  - mkdir -p sdk-reference-parser-unity-ue/dist
  - mv Documentation/Autogen/html/ sdk-reference-parser-unity-ue/src >/dev/null
  - cd sdk-reference-parser-unity-ue
  - npm install
  - npm start
  - mv -v dist/html/* dist >/dev/null
  - cd dist && zip -r $CI_PROJECT_DIR/build.zip * >/dev/null
  artifacts:
    paths:
    - build.zip
  tags:
    - devops

deploy doc:
  stage: deploy
  extends:      .deploy doc
  only:
    - /^v.*/
  dependencies:
    - build doc
  environment:
    name: doc/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.doc.srv.local/$URL_SLUG
    on_stop: stop doc
  when: manual
  tags:
    - sshclient

current doc:
  extends:      .current doc
  only:
    - /^v.*/
  dependencies:
    - deploy doc
  environment:
    name: doc/current
    url: https://developers.xsolla.com/sdk-code-references/unreal-store/
  tags:
    - sshclient

stop doc:
  extends:      .stop doc
  environment:
    name: doc/$CI_COMMIT_REF_SLUG
    action: stop
  only:
    - /^v.*/
  dependencies: []
  tags:
    - sshclient

# =================================================================================================================
# JOBS BASE

.win_job_base:
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - Builds
  dependencies: []
  tags:
    - sdk_ci
    - windows

.mac_job_base:
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - Builds
  dependencies: []
  tags:
    - sdk_ci
    - mac

# =================================================================================================================
# DEMO WINIDOWS

demo_win_52_inapp_browser:
  extends: .win_job_base
  stage: demo_win
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% %UE52_ENGINE_VERSION% Win64 False
  artifacts:
    name: "UE52_windows_inapp_browser_%CI_COMMIT_REF_NAME%"

demo_win_52_system_browser:
  extends: .win_job_base
  stage: demo_win
  when: manual
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% %UE52_ENGINE_VERSION% Win64 True
  artifacts:
    name: "UE52_windows_system_browser_%CI_COMMIT_REF_NAME%"

# =================================================================================================================
# DEMO ANDROID

demo_android_52_inapp_browser:
  extends: .win_job_base
  stage: demo_android
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% %UE52_ENGINE_VERSION% Android False
  artifacts:
    name: "UE52_android_inapp_browser_%CI_COMMIT_REF_NAME%"

demo_android_52_system_browser:
  extends: .win_job_base
  stage: demo_android
  when: manual
  script:
    - python %BUILD_DEMO_SCRIPT% %CI_PROJECT_DIR% %CI_COMMIT_REF_NAME% %UE52_ENGINE_VERSION% Android True
  artifacts:
    name: "UE52_android_system_browser_%CI_COMMIT_REF_NAME%"

# =================================================================================================================
# DEMO IOS

demo_ios_52_inapp_browser:
  extends: .mac_job_base
  stage: demo_ios
  script:
    - python3 $BUILD_DEMO_SCRIPT $CI_PROJECT_DIR $CI_COMMIT_REF_NAME $UE52_ENGINE_VERSION IOS False
  artifacts:
    name: "UE52_ios_inapp_browser_%CI_COMMIT_REF_NAME%"

demo_ios_52_system_browser:
  extends: .mac_job_base
  stage: demo_ios
  when: manual
  script:
    - python3 $BUILD_DEMO_SCRIPT $CI_PROJECT_DIR $CI_COMMIT_REF_NAME $UE52_ENGINE_VERSION IOS True
  artifacts:
    name: "UE52_ios_system_browser_%CI_COMMIT_REF_NAME%"
