include:
  - project: 'sysadm-docker/ubuntu-sshclient'
    ref:     'master'
    file:    'gitlab-ci-template.yml'

stages:
  - build
  - deploy
  - linking

variables:
    BUILD_SCRIPT_PATH: "CI\\ue_build_automation.py"
    PROJECT_PATH: "%cd%"
    BUILD_ROOT_PATH: "Builds"
    COMMERCE_SDK_NAME: "UeCommerceSdk"
    GIT_CLEAN_FLAGS: -ffdx
    GIT_CURRENT_BRANCH: $CI_COMMIT_BRANCH

build doc:
  stage: build
  only:
    - /^v.*/
  image: alpine
  script:
  - apk update && apk add doxygen graphviz ttf-freefont zip git nodejs npm
  - doxygen Documentation/Autogen/Doxyfile >/dev/null
  - git clone -b test https://$GITHUB_ACCESS_TOKEN@github.com/xsolla/sdk-reference-parser-unity-ue.git
  - mkdir -p sdk-reference-parser-unity-ue/src
  - mkdir -p sdk-reference-parser-unity-ue/dist
  - mv Documentation/Autogen/html/ sdk-reference-parser-unity-ue/src >/dev/null
  - cd sdk-reference-parser-unity-ue
  - npm install
  - npm start
  - mv -v dist/html/* dist >/dev/null
  - cd dist && zip -r $CI_PROJECT_DIR/build.zip * >/dev/null
  artifacts:
    paths:
    - build.zip
  tags:
    - devops

deploy doc:
  stage: deploy
  extends:      .deploy doc
  only:
    - /^v.*/
  dependencies:
    - build doc
  environment:
    name: doc/$CI_COMMIT_REF_SLUG
    url: https://$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME.doc.srv.local/$URL_SLUG
    on_stop: stop doc
  when: manual
  tags:
    - sshclient

current doc:
  extends:      .current doc
  only:
    - /^v.*/
  dependencies:
    - deploy doc
  environment:
    name: doc/current
    url: https://developers.xsolla.com/sdk-code-references/ue4-store
  tags:
    - sshclient

stop doc:
  extends:      .stop doc
  environment:
    name: doc/$CI_COMMIT_REF_SLUG
    action: stop
  only:
    - /^v.*/
  dependencies: []
  tags:
    - sshclient